language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install --dev --no-interaction

script:
    - mkdir -p tmp
    - vendor/bin/phpunit --coverage-text