language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install --dev --no-interaction

script:
    - mkdir -p tmp
    - if [[ "$TRAVIS_PHP_VERSION" == '5.4' ]]; then phpunit --coverage-text ; fi
    - if [[ "$TRAVIS_PHP_VERSION" == '5.5' ]]; then phpunit --coverage-text ; fi
    - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpunit --coverage-text ; fi
    - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then vendor/bin/phpunit --coverage-text ; fi
    - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then vendor/bin/phpunit --coverage-text ; fi